apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
    
      name: frontend
      labels:
        app: frontend-app
        tier: frontend
    spec:
      containers:
        - name: todo-frontend
          image: engcj/todo-frontend
          ports:
            - containerPort: 80
          env:
            - name: VITE_title
              value: "HELLO TODO FROM REACT"
            - name: VITE_api
              value: "http://backend-service:500/"
    